server:
  port: 6887
  servlet:
    context-path: /

spring:
  application:
    name: ai-agenda-backend

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_agenda_db?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}

  ai:
    openai:
      api-key: ${SILICONFLOW_API_KEY:}
      base-url: https://api.siliconflow.cn/
      chat:
        options:
          model: deepseek-ai/DeepSeek-V3.2
          temperature: 0.8
          enable_thinking: false


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.agenda.pojo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    org.springframework.web: info
jwt:
  secret: ${JWT_SECRET:ThisIsADevelopmentOnlyJwtSecretForAiAgendaAndShouldBeChangedBeforeProduction1234567890}
  expiration: 86400
